# localization.py

LANGUAGES = {
    "zh": {
        # General
        "page_title": "个人技能树",
        "nav_title": "导航",
        "view_switcher": "切换视图",
        "home_view": "🏠 技能树看板",
        "manage_view": "⚙️ 知识框架管理",
        "language": "语言",
        
        # Header
        "main_title": "🌳 全能技能树管理系统",
        
        # Sidebar
        "nav_header": "🧭 知识导航",
        "nav_select_label": "聚焦路径 / 快速预设",
        "nav_show_all": "(显示全部)",
        "add_skill_header": "📌 录入新技能点",
        
        "path_box_title": "1. 选择知识框架路径",
        "cat_l1": "一级分类",
        "cat_l2": "二级分类",
        "cat_l3": "三级分类",
        "path_to_be_added_to": "📍 将录入到: {path}",
        "path_prompt": "⚠️ 请先选择一个路径",
        
        "details_box_title": "2. 填写技能详情",
        "skill_name_label": "技能/能力名称",
        "skill_name_placeholder": "如：C++内存管理",
        "proficiency_label": "掌握程度",
        "priority_label": "优先级",
        "memo_label": "备注/证明",
        "memo_placeholder": "记录项目链接、关键笔记...",
        
        "submit_button": "同步到数据中心",
        "clear_data_button": "🗑️ 清空所有数据",
        "clear_data_help": "警告：这将永久删除所有技能记录",
        
        # Main content
        "top_tasks_header": "🚀 {scope} - 最迫切任务 (Top 3)",
        "top_tasks_global_scope": "全局",
        "urgency_metric": "紧迫度: {score}",
        "priority_metric": "优先级: {prio}",
        "path_metric": "📍 路径: {path}",
        "panorama_header": "📊 技能全景视图",
        
        "tab_list": "📋 列表模式",
        "tab_tree": "🕸️ 拓扑树状图",
        
        "col_path": "知识框架",
        "col_name": "技能名称",
        "col_proficiency": "熟练度",
        "col_priority": "优先级",
        "col_urgency": "紧迫度",
        "col_memo": "备注/证明",
        
        "edit_mode_toggle": "✏️ 编辑模式",
        "save_changes_button": "💾 保存表格修改",
        
        "tree_legend": "图例颜色：⬜ 待了解(0) | 🟥 入门(1) | 🟨 熟练 (2-3) | 🟩 精通 (4-5) | ⭐ 星号数量代表优先级",
        "empty_tree_info": "💡 你的技能树还是空的。请通过左侧边栏开始录入你的第一项能力。",
        
        # Management Page
        "manage_page_title": "⚙️ 知识框架管理",
        "manage_page_info": "在此处维护你的知识分类体系。修改或删除路径将引导你处理关联的技能。",
        "add_path_header": "➕ 添加新路径",
        "select_parent_step1": "第一步：选择父节点",
        "select_parent_help": "选择一个已有的节点作为父级，或选择顶级来创建全新的分类树。",
        "parent_top_level": "(作为顶级路径)",
        "add_child_step2": "第二步：输入新子节点名称",
        "add_child_placeholder": "例如: LLM",
        "add_node_button": "✔️ 添加新节点",
        
        "manual_path_expander": "...或手动输入完整路径 (高级)",
        "manual_path_input": "输入新路径 (例如: 技术.AI.LLM)",
        "manual_add_button": "添加手动路径",

        "edit_path_header": "🔧 修改/迁移路径",
        "select_path_to_edit": "选择要修改的路径节点",
        "action_type_label": "操作类型",
        "action_rename": "重命名 / 迁移",
        "action_delete": "删除",
        "action_order": "排序",
        "rename_to_label": "修改为 (新路径)",
        "rename_recursive_checkbox": "同时修改所有子节点 (例如: 修改 '技术' 会同步修改 '技术.编程')",
        "rename_confirm_button": "确认修改",
        "delete_warning": "⚠️ 删除路径节点 '{path}' 仅会从【预设列表】中移除。",
        "delete_caption": "已录入的技能将保留该路径，但该路径将不再作为推荐选项出现在录入菜单中（除非它仍被技能使用）。",
        "delete_confirm_button": "确认删除",
        "action_move_up": "向上",
        "action_move_down": "向下",
        "edit_skill_header": "编辑技能",
        "save_skill_button": "保存更改",
        
        "show_skill_nodes": "显示能力子节点",
        "graph_header": "🕸️ 知识框架全景图",
        "empty_graph_info": "💡 你的技能树还是空的，暂无图可显示。",
        
        # Alerts & Status
        "error_skill_name_empty": "请输入技能名称",
        "error_path_empty": "请选择一个知识框架路径",
        "success_skill_added": "已成功记录: {name}",
        "error_name_empty": "名称不能为空或只有空格。",
        "warning_path_exists": "该路径已存在",
        "success_path_added": "路径已添加: {path}",
        "error_path_input_empty": "请输入路径",
        "success_path_updated": "✅ 修改成功！已更新 {count} 个相关技能。",
        "warning_path_not_changed": "请修改路径名称",
        "success_path_removed": "已从预设中移除: {path}",
        "info_path_not_in_presets": "该路径不在预设列表中 (可能是由技能数据自动生成的)。",
        "error_empty_name_in_table": "⚠️ 保存失败：存在【技能名称】为空的数据行。",
        "success_data_updated": "数据已更新！",
        
        "profile_selector_label": "选择配置文件",
        "profile_management_header": "🗃️ 配置文件管理",
        "add_profile_header": "创建新配置",
        "new_profile_name_label": "新配置文件名称",
        "new_profile_name_placeholder": "例如: '工作规划' 或 '学习目标'",
        "create_profile_button": "创建新配置文件",
        "profile_creation_success": "✅ 成功创建配置文件: {name}",
        "profile_creation_error_exists": "❌ 创建失败: 配置文件 '{name}' 已存在。",
        "profile_creation_error_empty": "❌ 请输入有效的配置文件名称。"
    },
    "en": {
        "page_title": "Personal Skill Tree",
        "nav_title": "Navigation",
        "view_switcher": "Switch View",
        "home_view": "🏠 Skill Dashboard",
        "manage_view": "⚙️ Framework Management",
        "language": "Language",
        "main_title": "🌳 Universal Skill Tree Management System",
        "nav_header": "🧭 Knowledge Navigation",
        "nav_select_label": "Focus Path / Quick Preset",
        "nav_show_all": "(Show All)",
        "add_skill_header": "📌 Add New Skill",
        "path_box_title": "1. Select Knowledge Framework Path",
        "cat_l1": "Category L1",
        "cat_l2": "Category L2",
        "cat_l3": "Category L3",
        "path_to_be_added_to": "📍 Will be added to: {path}",
        "path_prompt": "⚠️ Please select a path first",
        "details_box_title": "2. Fill in Skill Details",
        "skill_name_label": "Skill/Ability Name",
        "skill_name_placeholder": "e.g., C++ Memory Management",
        "proficiency_label": "Proficiency",
        "priority_label": "Priority",
        "memo_label": "Memo/Proof",
        "memo_placeholder": "Record project links, key notes...",
        "submit_button": "Sync to Data Center",
        "clear_data_button": "🗑️ Clear All Data",
        "clear_data_help": "Warning: This will permanently delete all skill records",
        "top_tasks_header": "🚀 {scope} - Top 3 Urgent Tasks",
        "top_tasks_global_scope": "Global",
        "urgency_metric": "Urgency: {score}",
        "priority_metric": "Priority: {prio}",
        "path_metric": "📍 Path: {path}",
        "panorama_header": "📊 Skill Panorama",
        "tab_list": "📋 List Mode",
        "tab_tree": "🕸️ Topology Tree",
        "col_path": "Knowledge Framework",
        "col_name": "Skill Name",
        "col_proficiency": "Proficiency",
        "col_priority": "Priority",
        "col_urgency": "Urgency",
        "col_memo": "Memo/Proof",
        "edit_mode_toggle": "✏️ Edit Mode",
        "save_changes_button": "💾 Save Table Changes",
        "tree_legend": "Legend: ⬜ Unfamiliar(0) | 🟥 Beginner(1) | 🟨 Familiar(2-3) | 🟩 Proficient(4-5) | ⭐ Stars for Priority",
        "empty_tree_info": "💡 Your skill tree is empty. Start by adding your first skill via the sidebar.",
        "manage_page_title": "⚙️ Knowledge Framework Management",
        "manage_page_info": "Maintain your knowledge classification system here. Modifying or deleting paths will guide you to handle associated skills.",
        "add_path_header": "➕ Add New Path",
        "select_parent_step1": "Step 1: Select Parent Node",
        "select_parent_help": "Select an existing node as the parent, or choose top-level to create a new tree.",
        "parent_top_level": "(As Top-Level Path)",
        "add_child_step2": "Step 2: Enter New Child Node Name",
        "add_child_placeholder": "e.g., LLM",
        "add_node_button": "✔️ Add New Node",
        "manual_path_expander": "...or manually enter full path (Advanced)",
        "manual_path_input": "Enter new path (e.g., Tech.AI.LLM)",
        "manual_add_button": "Add Manual Path",
        "edit_path_header": "🔧 Modify/Migrate Path",
        "select_path_to_edit": "Select path node to modify",
        "action_type_label": "Action Type",
        "action_rename": "Rename / Migrate",
        "action_delete": "Delete",
        "action_order": "Order",
        "rename_to_label": "Rename to (New Path)",
        "rename_recursive_checkbox": "Modify all child nodes simultaneously (e.g., changing 'Tech' will also change 'Tech.Programming')",
        "rename_confirm_button": "Confirm Change",
        "delete_warning": "⚠️ Deleting path node '{path}' only removes it from the [Preset List].",
        "delete_caption": "Skills already entered will retain this path, but it will no longer appear as a recommended option in the input menu (unless still in use by a skill).",
                "delete_confirm_button": "Confirm Deletion",
                "action_move_up": "Up",
                "action_move_down": "Down",
                "edit_skill_header": "Edit Skill",
                "save_skill_button": "Save Changes",
        
                "show_skill_nodes": "Show skill sub-nodes",
                "graph_header": "🕸️ Knowledge Framework Panorama",
        "empty_graph_info": "💡 Your skill tree is empty, no graph to display yet.",
        "error_skill_name_empty": "Please enter a skill name",
        "error_path_empty": "Please select a knowledge framework path",
        "success_skill_added": "Successfully recorded: {name}",
        "error_name_empty": "Name cannot be empty or just spaces.",
        "warning_path_exists": "This path already exists",
        "success_path_added": "Path added: {path}",
        "error_path_input_empty": "Please enter a path",
        "success_path_updated": "✅ Success! Updated {count} related skills.",
        "warning_path_not_changed": "Please change the path name",
        "success_path_removed": "Removed from presets: {path}",
        "info_path_not_in_presets": "This path is not in the preset list (it might be auto-generated from skill data).",
        "error_empty_name_in_table": "⚠️ Save failed: A row with an empty [Skill Name] exists.",
        "success_data_updated": "Data has been updated!",
        
        "profile_selector_label": "Select Profile",
        "profile_management_header": "🗃️ Profile Management",
        "add_profile_header": "Create New Profile",
        "new_profile_name_label": "New Profile Name",
        "new_profile_name_placeholder": "e.g., 'Career Plan' or 'Learning Goals'",
        "create_profile_button": "Create New Profile",
        "profile_creation_success": "✅ Successfully created profile: {name}",
        "profile_creation_error_exists": "❌ Creation failed: Profile '{name}' already exists.",
        "profile_creation_error_empty": "❌ Please enter a valid profile name.",
        "import_button": "Import",
        "export_button": "Export",
        "import_success": "✅ Data imported successfully!",
        "import_error": "❌ Import failed: Invalid JSON file.",
        "export_label": "Download your skill tree"
    },
    "ja": {
        "page_title": "個人スキルツリー",
        "nav_title": "ナビゲーション",
        "view_switcher": "ビューを切り替え",
        "home_view": "🏠 スキルダッシュボード",
        "manage_view": "⚙️ フレームワーク管理",
        "language": "言語",
        "main_title": "🌳 汎用スキルツリー管理システム",
        "nav_header": "🧭 知識ナビゲーション",
        "nav_select_label": "パスにフォーカス / クイックプリセット",
        "nav_show_all": "(すべて表示)",
        "add_skill_header": "📌 新規スキルを追加",
        "path_box_title": "1. 知識フレームワークパスを選択",
        "cat_l1": "第一階層",
        "cat_l2": "第二階層",
        "cat_l3": "第三階層",
        "path_to_be_added_to": "📍 追加先: {path}",
        "path_prompt": "⚠️ まずパスを選択してください",
        "details_box_title": "2. スキルの詳細を入力",
        "skill_name_label": "スキル/能力名",
        "skill_name_placeholder": "例：C++メモリ管理",
        "proficiency_label": "習熟度",
        "priority_label": "優先度",
        "memo_label": "メモ/証明",
        "memo_placeholder": "プロジェクトリンクやキーノートを記録...",
        "submit_button": "データセンターに同期",
        "clear_data_button": "🗑️ 全データを消去",
        "clear_data_help": "警告：これにより、すべてのスキル記録が永久に削除されます",
        "top_tasks_header": "🚀 {scope} - 最も緊急なタスク (トップ3)",
        "top_tasks_global_scope": "グローバル",
        "urgency_metric": "緊急度: {score}",
        "priority_metric": "優先度: {prio}",
        "path_metric": "📍 パス: {path}",
        "panorama_header": "📊 スキルパノラマ",
        "tab_list": "📋 リストモード",
        "tab_tree": "🕸️ トポロジーツリー",
        "col_path": "知識フレームワーク",
        "col_name": "スキル名",
        "col_proficiency": "習熟度",
        "col_priority": "優先度",
        "col_urgency": "緊急度",
        "col_memo": "メモ/証明",
        "edit_mode_toggle": "✏️ 編集モード",
        "save_changes_button": "💾 テーブルの変更を保存",
        "tree_legend": "凡例: ⬜ 未習熟(0) | 🟥 初心者(1) | 🟨 習熟(2-3) | 🟩 精通(4-5) | ⭐ 星は優先度",
        "empty_tree_info": "💡 スキルツリーは空です。サイドバーから最初のスキルを追加してください。",
        "manage_page_title": "⚙️ 知識フレームワーク管理",
        "manage_page_info": "ここで知識分類体系を維持します。パスを変更または削除すると、関連スキルの処理が案内されます。",
        "add_path_header": "➕ 新規パスを追加",
        "select_parent_step1": "ステップ1：親ノードを選択",
        "select_parent_help": "既存のノードを親として選択するか、トップレベルを選択して新しいツリーを作成します。",
        "parent_top_level": "(トップレベルパスとして)",
        "add_child_step2": "ステップ2：新しい子ノード名を入力",
        "add_child_placeholder": "例: LLM",
        "add_node_button": "✔️ 新規ノードを追加",
        "manual_path_expander": "...またはフルパスを手動で入力 (上級者向け)",
        "manual_path_input": "新規パスを入力 (例: 技術.AI.LLM)",
        "manual_add_button": "手動パスを追加",
        "edit_path_header": "🔧 パスの変更/移行",
        "select_path_to_edit": "変更するパスノードを選択",
        "action_type_label": "アクションタイプ",
        "action_rename": "名前の変更 / 移行",
        "action_delete": "削除",
        "action_order": "順序",
        "rename_to_label": "新しい名前に変更 (新規パス)",
        "rename_recursive_checkbox": "すべての子ノードを同時に変更 (例: '技術'を変更すると'技術.プログラミング'も変更されます)",
        "rename_confirm_button": "変更を確定",
        "delete_warning": "⚠️ パスノード '{path}' の削除は【プリセットリスト】からのみ削除します。",
        "delete_caption": "既に入力されたスキルはこのパスを保持しますが、入力メニューの推奨オプションとしては表示されなくなります（スキルによってまだ使用されている場合を除く）。",
                "delete_confirm_button": "削除を確定",
                "action_move_up": "上へ",
                "action_move_down": "下へ",
                "edit_skill_header": "スキルを編集",
                "save_skill_button": "変更を保存",
        
                "show_skill_nodes": "スキルサブノードを表示",
                "graph_header": "🕸️ 知識フレームワークパノラマ",
        "empty_graph_info": "💡 スキルツリーは空で、表示するグラフがまだありません。",
        "error_skill_name_empty": "スキル名を入力してください",
        "error_path_empty": "知識フレームワークパスを選択してください",
        "success_skill_added": "正常に記録されました: {name}",
        "error_name_empty": "名前は空またはスペースのみにできません。",
        "warning_path_exists": "このパスは既に存在します",
        "success_path_added": "パスが追加されました: {path}",
        "error_path_input_empty": "パスを入力してください",
        "success_path_updated": "✅ 成功！関連スキルを {count} 個更新しました。",
        "warning_path_not_changed": "パス名を変更してください",
        "success_path_removed": "プリセットから削除しました: {path}",
        "info_path_not_in_presets": "このパスはプリセットリストにありません（スキルデータから自動生成された可能性があります）。",
        "error_empty_name_in_table": "⚠️ 保存失敗：[スキル名]が空の行が存在します。",
        "success_data_updated": "データが更新されました！",
        
        "profile_selector_label": "プロファイルを選択",
        "profile_management_header": "🗃️ プロファイル管理",
        "add_profile_header": "新規プロファイル作成",
        "new_profile_name_label": "新しいプロファイル名",
        "new_profile_name_placeholder": "例: 「キャリアプラン」や「学習目標」",
        "create_profile_button": "新しいプロファイルを作成",
        "profile_creation_success": "✅ プロファイルが正常に作成されました: {name}",
        "profile_creation_error_exists": "❌ 作成に失敗しました: プロファイル '{name}' は既に存在します。",
        "profile_creation_error_empty": "❌ 有効なプロファイル名を入力してください。",
        "import_button": "インポート",
        "export_button": "エクスポート",
        "import_success": "✅ データが正常にインポートされました！",
        "import_error": "❌ インポートに失敗しました：無効なJSONファイルです。",
        "export_label": "スキルツリーをダウンロード"
    }
}
